# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' read
#'
#' Generic fast read
#'
#' @param path File path
#' @param lines As text lines file
#' @importFrom Rcpp evalCpp
#' @export
read <- function(path, lines) {
    .Call(`_loudness_read`, path, lines)
}

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call(`_loudness_timesTwo`, x)
}

